In [275]:
import pandas as pd

In [276]:
df1 = pd.read_csv("../data/cruated/combined_population_affluence_postcode.csv")

In [277]:
# drop the missing value in postcode column (caused by when sa2 code transfered to postcode)
indexes_to_drop = df1[df1['postcode'] == 0].index

df1 = df1.drop(indexes_to_drop)

In [278]:
df1.columns

Index(['GCCSA code', 'GCCSA name', 'SA4 code', 'SA4 name', 'SA3 code',
       'SA3 name', 'postcode', 'SA2 code', 'SA2 name', '2001_population',
       '2002_population', '2003_population', '2004_population',
       '2005_population', '2006_population', '2007_population',
       '2008_population', '2009_population', '2010_population',
       '2011_population', '2012_population', '2013_population',
       '2014_population', '2015_population', '2016_population',
       '2017_population', '2018_population', '2019_population',
       '2020_population', '2021_population', '2022_population',
       '2023_population', 'ERP_2023_change_number',
       'ERP_2023_change_percentage(%)', 'natural_2023_increase_number',
       'internal_2023_migration_number', 'overseas_2023_migration_number',
       'area_in_square_kilometers', 'population_density_2023',
       'estimated_2024_population', 'IEO_Score', 'IEO_State Rank',
       'IEO_State Decile', 'IEO_State Percentile',
       'IER_Usual Resident Population', 'IER_Score', 'IER_State Rank',
       'IER_State Decile', 'IER_State Percentile'],
      dtype='object')

In [279]:
# 1. sum all population number 
agg_dict = {f'{year}_population': 'sum' for year in range(2001, 2024)}

agg_dict['ERP_2023_change_number'] = 'sum'
agg_dict['natural_2023_increase_number'] = 'sum'
agg_dict['natural_2023_increase_number'] = 'sum'
agg_dict['internal_2023_migration_number'] = 'sum'
agg_dict['overseas_2023_migration_number'] = 'sum'
agg_dict['area_in_square_kilometers'] = 'sum'
agg_dict['estimated_2024_population'] = 'sum'

agg_dict['IEO_Score'] = 'mean'
agg_dict['IEO_State Rank'] = 'mean'
agg_dict['IEO_State Decile'] = 'mean'
agg_dict['IEO_State Percentile'] = 'mean'


agg_dict['IER_Usual Resident Population'] = 'sum'
agg_dict['IER_Score'] = 'mean'
agg_dict['IER_State Rank'] = 'mean'
agg_dict['IER_State Decile'] = 'mean'
agg_dict['IER_State Percentile'] = 'mean'


df_grouped = df1.groupby('postcode').agg(agg_dict).reset_index()

In [280]:
df_grouped.head(20)

,postcode,2001_population,2002_population,2003_population,2004_population,2005_population,2006_population,2007_population,2008_population,2009_population,...,estimated_2024_population,IEO_Score,IEO_State Rank,IEO_State Decile,IEO_State Percentile,IER_Usual Resident Population,IER_Score,IER_State Rank,IER_State Decile,IER_State Percentile
0,3000,7644,9592,11400,12727,14292,15249,16225,17325,18751,...,62187,1142.276830,475.000000,10.000000,92.666667,42366.0,754.877783,2.333333,1.000000,1.000000
1,3002,3731,3859,4243,4460,4495,4555,4806,5055,5202,...,5319,1188.740162,515.000000,10.000000,100.000000,4896.0,980.316756,164.000000,4.000000,32.000000
2,3003,2413,2503,2570,2748,2903,3072,3216,3419,3587,...,9483,1150.352472,483.000000,10.000000,94.000000,7446.0,881.657306,16.000000,1.000000,4.000000
3,3004,8558,8675,8836,8965,9145,9340,9650,9924,10268,...,14188,1122.288055,451.000000,9.000000,88.000000,11857.0,904.283085,34.000000,1.000000,7.000000
4,3006,4330,5645,7102,8167,9097,9863,10697,11408,11931,...,28292,1154.227791,487.000000,10.000000,94.500000,22564.0,874.637200,15.000000,1.000000,3.500000
5,3008,154,926,1913,3089,3779,4152,4592,5040,5402,...,19052,1159.821114,496.000000,10.000000,96.000000,15493.0,875.226913,14.000000,1.000000,3.000000
6,3011,19645,19641,19733,19772,19933,20129,20441,20927,21384,...,31749,1106.149338,429.500000,8.500000,83.500000,26378.0,951.829308,139.000000,3.000000,27.500000
7,3012,9807,9801,9825,9879,9988,10152,10307,10543,10700,...,13222,1078.175187,386.000000,8.000000,75.000000,11735.0,962.727539,125.000000,3.000000,25.000000
8,3013,12573,12549,12686,12854,13006,13205,13536,13815,14030,...,16388,1115.249603,443.000000,9.000000,86.000000,15463.0,1035.130609,326.000000,7.000000,64.000000
9,3015,14723,14823,14921,14984,15186,15474,15864,16182,16493,...,20033,1110.016603,437.000000,9.000000,85.000000,18753.0,1045.806674,372.000000,8.000000,73.000000
10,3016,14056,14275,14363,14449,14550,14751,14950,15119,15400,...,17001,1112.570498,442.000000,9.000000,86.000000,15912.0,1040.012611,351.000000,7.000000,69.000000
11,3018,12221,12120,12045,11919,11864,11857,11915,12041,12152,...,14066,1054.047011,346.000000,7.000000,67.000000,13556.0,1006.533674,247.000000,5.000000,49.000000
12,3019,12851,12995,13028,13039,13184,13482,14178,14881,15633,...,20897,1009.077760,264.000000,6.000000,52.000000,19068.0,917.917770,50.000000,1.000000,10.000000
13,3020,35158,35131,35064,35110,35160,35300,35442,35931,36748,...,41536,946.349916,114.666667,2.666667,22.333333,40050.0,930.039159,59.333333,2.000000,12.000000
14,3021,51679,51219,50509,50074,49768,49365,49388,49760,50282,...,52966,892.923628,23.666667,1.000000,5.000000,52018.0,901.048162,32.000000,1.333333,6.666667
15,3022,6640,6597,6560,6523,6523,6556,6559,6758,7087,...,7950,970.384149,167.000000,4.000000,33.000000,7502.0,893.529729,24.000000,1.000000,5.000000
16,3023,19048,21733,25102,28636,31930,34831,38379,41987,46337,...,62897,973.385201,179.200000,4.000000,35.200000,60584.0,1028.572712,319.200000,6.800000,62.600000
17,3024,9631,10039,10505,11084,12203,13351,14610,16036,17616,...,90071,1005.993621,254.600000,5.400000,49.600000,60879.0,1039.031017,344.400000,7.200000,67.600000
18,3025,13206,13121,12995,12906,12869,12844,12877,12974,13150,...,15710,1010.983857,272.000000,6.000000,53.000000,14931.0,962.758368,126.000000,3.000000,25.000000
19,3026,76,149,347,591,1037,1556,2366,3192,4303,...,8975,992.624334,224.000000,5.000000,44.000000,8653.0,1050.817938,388.000000,8.000000,76.000000

In [281]:
df_grouped['ERP_2023_change_percentage(%)'] = ((df_grouped['ERP_2023_change_number'] / df_grouped['2023_population']) * 100).round(2)

df_grouped['population_density_2023'] = (df_grouped['2023_population'] / df_grouped['area_in_square_kilometers']).round(2)


df_grouped = df_grouped.round(2)

In [282]:
df_grouped.to_csv("../data/cruated/final_cleaned_affu_popu.csv", index=False)