In [44]:
import pandas as pd
import geopandas as gpd

regions_df = pd.read_csv('../../data/raw/location/sa2_to_rental_suburb_groups.csv')
regions_df['geometry'] = gpd.GeoSeries.from_wkt(regions_df['geometry'])

regions_df = gpd.GeoDataFrame(
    regions_df,
    geometry='geometry'
)

def fix_col_names(df):
    df.columns = df.columns.str.lower().str.replace(' ', '_')

In [3]:
regions_df

,Unnamed: 0,geometry,suburbs,regions,code
0,0,"POLYGON ((144.97018 -37.8607, 144.96997 -37.86...",Albert Park-Middle Park-West St Kilda,"['Albert Park', 'St Kilda - West']","[206051128, 206051514]"
1,1,"POLYGON ((144.79015 -37.86216, 144.78952 -37.8...",Altona,"['Altona', 'Altona North']","[213021341, 213021343]"
2,2,"POLYGON ((145.01167 -37.85357, 145.01177 -37.8...",Armadale,['Armadale'],[206061135]
3,3,"POLYGON ((145.12549 -38.07134, 145.12536 -38.0...",Aspendale-Chelsea-Carrum,"['Carrum - Patterson Lakes', 'Edithvale - Aspe...","[208031189, 208031186, 208031185]"
4,4,"POLYGON ((147.57603 -37.83022, 147.57594 -37.8...",Bairnsdale,['Bairnsdale'],[205021081]
...,...,...,...,...,...
139,139,"POLYGON ((144.86314 -37.79333, 144.8632 -37.79...",West Footscray,['West Footscray - Tottenham'],[213031351]
140,140,"POLYGON ((144.99578 -37.47133, 144.99981 -37.4...",Whittlesea,['Whittlesea'],[209041225]
141,141,"POLYGON ((144.887 -37.85079, 144.8873 -37.8501...",Williamstown,['Williamstown'],[213021346]
142,142,"POLYGON ((146.77394 -36.12801, 146.77189 -36.1...",Wodonga,"['Wodonga', 'West Wodonga']","[204031492, 204031073]"
143,143,"POLYGON ((144.85984 -37.81382, 144.86022 -37.8...",Yarraville-Seddon,"['Yarraville', 'Seddon - Kingsville']","[213031352, 213031350]"

In [40]:
CRIME = '../../data/landing/crime/Data_Tables_LGA_Recorded_Offences_Year_Ending_June_2024.csv'
crime_df = pd.read_csv(CRIME)

fix_col_names(crime_df)

crime_df

,year,year_ending,local_government_area,postcode,suburb/town_name,offence_division,offence_subdivision,offence_subgroup,offence_count
0,2024,June,Alpine,3691,Dederang,B Property and deception offences,B40 Theft,B42 Steal from a motor vehicle,1
1,2024,June,Alpine,3691,Dederang,B Property and deception offences,B40 Theft,B49 Other theft,1
2,2024,June,Alpine,3691,Dederang,D Public order and security offences,D10 Weapons and explosives offences,D11 Firearms offences,3
3,2024,June,Alpine,3691,Dederang,D Public order and security offences,D10 Weapons and explosives offences,D13 Explosives offences,1
4,2024,June,Alpine,3691,Mongans Bridge,B Property and deception offences,B40 Theft,B49 Other theft,1
...,...,...,...,...,...,...,...,...,...
364133,2015,June,Yarriambiack,3488,Speed,B Property and deception offences,B40 Theft,B43 Steal from a retail store,1
364134,2015,June,Yarriambiack,3489,Tempy,B Property and deception offences,B30 Burglary/Break and enter,B322 Non-residential non-aggravated burglary,1
364135,2015,June,Yarriambiack,3489,Tempy,B Property and deception offences,B40 Theft,B42 Steal from a motor vehicle,1
364136,2015,June,Yarriambiack,3489,Tempy,E Justice procedures offences,E20 Breaches of orders,E22 Breach intervention order,1
364137,2015,June,Yarriambiack,3491,Patchewollock,E Justice procedures offences,E10 Justice procedures,E19 Other justice procedures offences,1

In [55]:
POSTAL_SUBURB = '../../data/landing/postal_shapefile/POA_2021_AUST_GDA2020.shp'
lga_df = gpd.read_file(POSTAL_SUBURB)

lga_proc_df = lga_df.copy() # [lga_df['STE_NAME21'] == 'Victoria']
lga_proc_df

fix_col_names(lga_proc_df)

# lga_df[lga_df['POA_NAME21'] == '3101']

lga_proc_df['postcode'] = lga_proc_df['poa_name21'].apply(pd.to_numeric, errors='coerce')

lga_proc_df_filtered = gpd.GeoDataFrame(
    lga_proc_df[['postcode', 'geometry']],
    geometry='geometry'
)

lga_proc_df_filtered

      postcode                                           geometry
0        800.0  POLYGON ((130.83681 -12.45376, 130.83684 -12.4...
1        810.0  POLYGON ((130.89986 -12.36567, 130.89875 -12.3...
2        812.0  POLYGON ((130.91915 -12.40786, 130.91831 -12.4...
3        820.0  POLYGON ((130.8526 -12.43994, 130.85089 -12.43...
4        822.0  MULTIPOLYGON (((136.56648 -12.08392, 136.56704...
...        ...                                                ...
2639    7469.0  MULTIPOLYGON (((144.79215 -41.46478, 144.79212...
2640    7470.0  POLYGON ((145.57769 -41.7864, 145.57686 -41.78...
2641       NaN                                               None
2642       NaN                                               None
2643       NaN                                               None

[2644 rows x 2 columns]

In [59]:
joined = pd.merge(crime_df, lga_proc_df_filtered, on='postcode')
# joined['geometry_right'] = joined['geometry']

# joined = gpd.GeoDataFrame(
#     joined,
#     geometry='geometry'
# )

joined

joined_gb = joined.groupby(['postcode']).agg({
    'geometry': 'first'
}).reset_index()

joined_gb = gpd.GeoDataFrame(
    joined_gb,
    geometry='geometry'
)

joined_gb['geometry_right'] = joined_gb['geometry']
joined_gb

,postcode,geometry,geometry_right
0,3000,"POLYGON ((144.96139 -37.8205, 144.96063 -37.82...","POLYGON ((144.96139 -37.8205, 144.96063 -37.82..."
1,3002,"POLYGON ((144.98978 -37.81906, 144.98973 -37.8...","POLYGON ((144.98978 -37.81906, 144.98973 -37.8..."
2,3003,"POLYGON ((144.95268 -37.8128, 144.95191 -37.81...","POLYGON ((144.95268 -37.8128, 144.95191 -37.81..."
3,3004,"POLYGON ((144.98001 -37.84422, 144.98031 -37.8...","POLYGON ((144.98001 -37.84422, 144.98031 -37.8..."
4,3006,"POLYGON ((144.96139 -37.8205, 144.96303 -37.82...","POLYGON ((144.96139 -37.8205, 144.96303 -37.82..."
...,...,...,...
688,3990,"POLYGON ((145.52915 -38.42196, 145.52883 -38.4...","POLYGON ((145.52915 -38.42196, 145.52883 -38.4..."
689,3991,"POLYGON ((145.51584 -38.46758, 145.51573 -38.4...","POLYGON ((145.51584 -38.46758, 145.51573 -38.4..."
690,3992,"POLYGON ((145.55759 -38.47959, 145.56055 -38.4...","POLYGON ((145.55759 -38.47959, 145.56055 -38.4..."
691,3995,"MULTIPOLYGON (((145.57364 -38.57838, 145.57356...","MULTIPOLYGON (((145.57364 -38.57838, 145.57356..."
692,3996,"POLYGON ((145.71387 -38.64553, 145.7138 -38.64...","POLYGON ((145.71387 -38.64553, 145.7138 -38.64..."

In [134]:

regions_df_w_crs = regions_df.copy() #.set_crs('EPSG:4326')

# join based on the largest intersecting area
intersecting_zones_df = gpd.sjoin(regions_df_w_crs, joined_gb, how='left', predicate='intersects')

intersecting_zones_df['overlap_area'] = intersecting_zones_df.apply(
    lambda row: row.geometry.intersection(row['geometry_right']).area 
    if not pd.isna(row['geometry_right']) else 0, axis=1
)
intersecting_zones_df['overlap_area'] = intersecting_zones_df['overlap_area'].fillna(0)

intersecting_zones_df = intersecting_zones_df.reset_index()

intersecting_zones_df['total_overlap_area_per_postcode'] = intersecting_zones_df.groupby('suburbs')['overlap_area'].transform('sum')

# Step 2: Normalize the overlap_area by dividing it by the total_overlap_area_per_postcode
intersecting_zones_df['normalized_overlap'] = intersecting_zones_df['overlap_area'] / intersecting_zones_df['total_overlap_area_per_postcode']

# intersecting_zones_df = intersecting_zones_df[intersecting_zones_df['normalized_overlap'] < 0.00001]
# intersecting_zones_df.groupby('suburbs').agg({'normalized_overlap': 'sum'})
# joined = pd.merge(crime_df, lga_proc_df_filtered, on='postcode')
intersecting_zones_df

,index,Unnamed: 0,geometry,suburbs,regions,code,index_right,postcode,geometry_right,overlap_area,total_overlap_area_per_postcode,normalized_overlap
0,0,0,"POLYGON ((144.97018 -37.8607, 144.96997 -37.86...",Albert Park-Middle Park-West St Kilda,"['Albert Park', 'St Kilda - West']","[206051128, 206051514]",159,3184,"POLYGON ((144.98435 -37.87244, 144.98485 -37.8...",1.019886e-06,0.000721,1.415317e-03
1,0,0,"POLYGON ((144.97018 -37.8607, 144.96997 -37.86...",Albert Park-Middle Park-West St Kilda,"['Albert Park', 'St Kilda - West']","[206051128, 206051514]",157,3182,"POLYGON ((144.98968 -37.85648, 144.9899 -37.85...",2.196142e-04,0.000721,3.047632e-01
2,0,0,"POLYGON ((144.97018 -37.8607, 144.96997 -37.86...",Albert Park-Middle Park-West St Kilda,"['Albert Park', 'St Kilda - West']","[206051128, 206051514]",156,3181,"POLYGON ((145.0107 -37.85625, 145.01066 -37.85...",6.014922e-06,0.000721,8.347032e-03
3,0,0,"POLYGON ((144.97018 -37.8607, 144.96997 -37.86...",Albert Park-Middle Park-West St Kilda,"['Albert Park', 'St Kilda - West']","[206051128, 206051514]",180,3206,"POLYGON ((144.95185 -37.83992, 144.95177 -37.8...",3.774483e-04,0.000721,5.237929e-01
4,0,0,"POLYGON ((144.97018 -37.8607, 144.96997 -37.86...",Albert Park-Middle Park-West St Kilda,"['Albert Park', 'St Kilda - West']","[206051128, 206051514]",181,3207,"POLYGON ((144.93979 -37.82545, 144.9401 -37.82...",8.337428e-13,0.000721,1.157002e-09
...,...,...,...,...,...,...,...,...,...,...,...,...
993,143,143,"POLYGON ((144.85984 -37.81382, 144.86022 -37.8...",Yarraville-Seddon,"['Yarraville', 'Seddon - Kingsville']","[213031352, 213031350]",18,3025,"POLYGON ((144.86438 -37.84044, 144.86438 -37.8...",3.021301e-13,0.000747,4.044597e-10
994,143,143,"POLYGON ((144.85984 -37.81382, 144.86022 -37.8...",Yarraville-Seddon,"['Yarraville', 'Seddon - Kingsville']","[213031352, 213031350]",8,3013,"POLYGON ((144.88986 -37.80977, 144.88992 -37.8...",5.790748e-04,0.000747,7.752038e-01
995,143,143,"POLYGON ((144.85984 -37.81382, 144.86022 -37.8...",Yarraville-Seddon,"['Yarraville', 'Seddon - Kingsville']","[213031352, 213031350]",2,3003,"POLYGON ((144.95268 -37.8128, 144.95191 -37.81...",1.160341e-12,0.000747,1.553342e-09
996,143,143,"POLYGON ((144.85984 -37.81382, 144.86022 -37.8...",Yarraville-Seddon,"['Yarraville', 'Seddon - Kingsville']","[213031352, 213031350]",6,3011,"POLYGON ((144.89394 -37.78794, 144.89466 -37.7...",9.376033e-05,0.000747,1.255164e-01
997,143,143,"POLYGON ((144.85984 -37.81382, 144.86022 -37.8...",Yarraville-Seddon,"['Yarraville', 'Seddon - Kingsville']","[213031352, 213031350]",7,3012,"POLYGON ((144.88482 -37.80582, 144.88471 -37.8...",7.416174e-05,0.000747,9.927986e-02

In [136]:
joined_all = pd.merge(intersecting_zones_df, joined, on='postcode')

joined_all['normalized_overlap'] = pd.to_numeric(joined_all['normalized_overlap'], errors='coerce')
joined_all['offence_count'] = pd.to_numeric(joined_all['offence_count'], errors='coerce') * joined_all['normalized_overlap'] 

# joined_all.value_counts('offence_subdivision')
cols = list(joined_all['offence_subdivision'].unique())
df_encoded = pd.get_dummies(joined_all, columns=['offence_subdivision'], drop_first=False)

for col in cols:
    df_encoded[col] = df_encoded['offence_subdivision_' + col] * df_encoded['offence_count']

df_encoded = df_encoded.groupby(['suburbs', 'year', 'year_ending']).sum(cols).reset_index()

df_encoded

,suburbs,year,year_ending,index,Unnamed: 0,index_right,postcode,overlap_area,total_overlap_area_per_postcode,normalized_overlap,...,D30 Public nuisance offences,E10 Justice procedures,E20 Breaches of orders,F20 Transport regulation offences,F90 Miscellaneous offences,C90 Other drug offences,F30 Other government regulatory offences,D40 Public security offences,F10 Regulatory driving offences,B60 Bribery
0,Albert Park-Middle Park-West St Kilda,2015,June,0,0,80853,1872225,0.063882,0.427319,88.650654,...,12.705750,71.891770,210.483706,1.109359,0.321457,9.142897e-01,10.106054,3.366460e+00,1.075971e+00,0.323363
1,Albert Park-Middle Park-West St Kilda,2016,June,0,0,82191,1894748,0.065603,0.432364,91.037996,...,21.437409,70.024278,282.063651,5.377950,2.360719,1.157002e-09,5.624394,1.606563e+00,4.664448e-01,0.161682
2,Albert Park-Middle Park-West St Kilda,2017,June,0,0,81191,1878614,0.063029,0.428761,87.466405,...,19.263091,67.259923,206.282406,4.132875,0.485045,1.616815e-01,3.362648,3.233631e-01,0.000000e+00,0.008347
3,Albert Park-Middle Park-West St Kilda,2018,June,0,0,82538,1904165,0.062894,0.434525,87.279885,...,22.246887,62.168070,209.469831,0.351235,2.360719,1.616815e-01,14.268730,4.813246e+00,1.178672e-08,0.485045
4,Albert Park-Middle Park-West St Kilda,2019,June,0,0,80645,1856986,0.061540,0.423716,85.400242,...,18.537230,79.682981,237.604554,4.574256,1.426281,8.347033e-03,1.532163,2.438106e+00,1.571379e+00,0.304763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435,Yarraville-Seddon,2020,June,77077,77077,4205,1623861,0.051574,0.402631,69.042282,...,17.112818,18.014514,80.695182,0.449593,10.797895,0.000000e+00,0.125516,0.000000e+00,0.000000e+00,0.000000
1436,Yarraville-Seddon,2021,June,78936,78936,4220,1662928,0.051644,0.412342,69.135895,...,5.896115,14.003182,74.811460,1.502065,63.338982,7.752038e-01,0.224796,0.000000e+00,1.553342e-09,0.000000
1437,Yarraville-Seddon,2022,June,80509,80509,4427,1696246,0.052766,0.420559,70.637961,...,11.647677,24.088032,123.170566,0.475829,16.347411,1.255164e-01,2.172323,0.000000e+00,0.000000e+00,0.000000
1438,Yarraville-Seddon,2023,June,79365,79365,4288,1672039,0.053835,0.414583,72.068518,...,16.078235,19.643156,117.863711,0.627582,0.125516,0.000000e+00,0.502065,1.553342e-09,0.000000e+00,0.000000
1439,Yarraville-Seddon,2024,June,77077,77077,4181,1623849,0.049619,0.402631,66.424497,...,9.074104,20.716674,125.408341,1.926957,0.376549,0.000000e+00,0.324076,0.000000e+00,0.000000e+00,0.000000

In [145]:
final_df = df_encoded[['suburbs', 'year', 'year_ending'] + cols].copy()
final_df['total_crimes'] = final_df[cols].sum(axis=1)
fix_col_names(final_df)
final_df.to_csv('../../data/raw/crime/crime.csv')
final_df

,suburbs,year,year_ending,a20_assault_and_related_offences,a50_robbery,"a70_stalking,_harassment_and_threatening_behaviour",a80_dangerous_and_negligent_acts_endangering_people,other_crimes_against_the_person,b10_arson,b20_property_damage,...,e10_justice_procedures,e20_breaches_of_orders,f20_transport_regulation_offences,f90_miscellaneous_offences,c90_other_drug_offences,f30_other_government_regulatory_offences,d40_public_security_offences,f10_regulatory_driving_offences,b60_bribery,total_crimes
0,Albert Park-Middle Park-West St Kilda,2015,June,178.045119,15.312481,89.447606,14.557886,71.608504,5.309056,161.823843,...,71.891770,210.483706,1.109359,0.321457,9.142897e-01,10.106054,3.366460e+00,1.075971e+00,0.323363,2586.271942
1,Albert Park-Middle Park-West St Kilda,2016,June,163.245015,18.871981,60.409599,12.829730,75.826735,8.872914,144.314600,...,70.024278,282.063651,5.377950,2.360719,1.157002e-09,5.624394,1.606563e+00,4.664448e-01,0.161682,2712.910871
2,Albert Park-Middle Park-West St Kilda,2017,June,168.857808,21.868907,51.808850,13.412846,77.006862,6.199418,146.561629,...,67.259923,206.282406,4.132875,0.485045,1.616815e-01,3.362648,3.233631e-01,0.000000e+00,0.008347,2789.178929
3,Albert Park-Middle Park-West St Kilda,2018,June,166.026923,20.091190,43.838102,13.860390,90.774467,3.861967,144.177434,...,62.168070,209.469831,0.351235,2.360719,1.616815e-01,14.268730,4.813246e+00,1.178672e-08,0.485045,2532.279242
4,Albert Park-Middle Park-West St Kilda,2019,June,183.604336,21.447080,43.146675,13.297669,80.959385,3.894443,133.539096,...,79.682981,237.604554,4.574256,1.426281,8.347033e-03,1.532163,2.438106e+00,1.571379e+00,0.304763,2518.652829
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435,Yarraville-Seddon,2020,June,86.750335,27.330328,19.202216,4.874009,49.340569,2.899185,100.302779,...,18.014514,80.695182,0.449593,10.797895,0.000000e+00,0.125516,0.000000e+00,0.000000e+00,0.000000,1324.241856
1436,Yarraville-Seddon,2021,June,69.643938,13.452273,17.923412,5.376074,24.320056,3.030367,95.957631,...,14.003182,74.811460,1.502065,63.338982,7.752038e-01,0.224796,0.000000e+00,1.553342e-09,0.000000,1232.578072
1437,Yarraville-Seddon,2022,June,95.210758,5.438345,26.109663,7.049403,31.686307,1.899185,94.692280,...,24.088032,123.170566,0.475829,16.347411,1.255164e-01,2.172323,0.000000e+00,0.000000e+00,0.000000,1283.131871
1438,Yarraville-Seddon,2023,June,97.019121,9.352908,21.195015,6.622976,32.999610,4.028832,131.906303,...,19.643156,117.863711,0.627582,0.125516,0.000000e+00,0.502065,1.553342e-09,0.000000e+00,0.000000,1401.943417
1439,Yarraville-Seddon,2024,June,99.848417,12.814894,18.733114,9.803561,27.770208,8.478425,124.552530,...,20.716674,125.408341,1.926957,0.376549,0.000000e+00,0.324076,0.000000e+00,0.000000e+00,0.000000,1565.947609